%YAML 1.2
# yamllint disable rule:line-length
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: 2026 Arne Magnus Tveita Løken <212174338+amtl-no@users.noreply.github.com>
# yamllint enable rule:line-length
---
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint.yaml'

rules:
  braces:
    forbid: non-empty
  brackets:
    forbid: false
  colons: enable
  commas: enable
  comments:
    min-spaces-from-content: 1
  comments-indentation: enable
  document-end:
    present: false
  document-start:
    present: true
  empty-lines: enable
  empty-values: disable
  hyphens: enable
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: true
  key-duplicates: enable
  key-ordering: disable
  line-length:
    max: 79
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values: enable
  quoted-strings:
    quote-type: single
    required: false
  trailing-spaces: enable
  truthy: enable
