[project]
name = "curriculum-vitae"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "ruff>=0.15.5",
]

[tool.ruff]
line-length = 79
target-version = "py312"

[tool.ruff.lint]
select = ["D", "E", "F", "I", "N", "U"]
ignore = [
	   "D203",
	   "D212"
]

[tool.ruff.lint.isort]
known-first-party = ["scripts"]
