%YAML 1.2
# yamllint disable rule:line-length
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: 2026 Arne Magnus Tveita Løken <212174338+amtl-no@users.noreply.github.com>
# yamllint enable rule:line-length
---
meta:
  license:
    spdx: CC-BY-4.0
  description: Moderncv casual theme configuration

template: moderncv/cv.tex.j2

documentclass:
  name: moderncv
  options:
    - a4paper
    - 10pt

packages:
  - name: geometry
    options:
      top: 0.65in
      bottom: 0.85in
      left: 0.75in
      right: 0.75in
  - name: babel
    options:
      lang: true
  - name: csquotes
  - name: fontspec
  - name: xurl
  - name: nowidow

theme:
  style: casual
  color: blue

photo:
  file: 'assets/photo.jpg'
  size: '48pt'

pre_commands:
  - >-
      \PassOptionsToPackage{colorlinks=true,urlcolor=[rgb]{{color1_rgb}}}
      {hyperref}

commands:
  - \recomputelengths
  - \setlength{\footskip}{0pt}
  - \setmainfont{Source Serif Pro}
  - \moderncvtheme[{color}]{{style}}
  - \patchcmd{\makeletterclosing}{[3em]}{[0.5em]}{}{}
  - \setlength{\hintscolumnwidth}{2cm}
  - \setlength{\parskip}{0pt}
  - \renewcommand{\namefont}{\fontsize{36}{38}\mdseries\upshape}
