%YAML 1.2
# yamllint disable rule:line-length
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: 2026 Arne Magnus Tveita Løken <212174338+amtl-no@users.noreply.github.com>
# yamllint enable rule:line-length
---
meta:
  license:
    spdx: CC-BY-4.0
  description: Moderncv casual theme configuration

template: moderncv/cv.tex.j2

documentclass:
  name: moderncv
  options:
    - a4paper
    - 10pt

packages:
  - name: geometry
    options:
      top: 0.85in
      bottom: 0.85in
      left: 0.85in
      right: 0.85in
  - name: babel
    options:
      lang: true
  - name: csquotes
  - name: fontspec
  - name: xurl
  - name: nowidow

theme:
  style: casual
  color: blue

pre_commands:
  - >-
    \PassOptionsToPackage{colorlinks=true,urlcolor=[rgb]{{color1_rgb}}}
    {hyperref}

commands:
  - \recomputelengths
  - \setlength{\footskip}{0pt}
  - \setmainfont{Source Serif Pro}
  - \moderncvtheme[{color}]{{style}}
  - \patchcmd{\makeletterclosing}{[3em]}{[1em]}{}{}
  - \setlength{\hintscolumnwidth}{2cm}
  - \setlength{\parskip}{0pt}
  
