# yamllint disable rule:line-length
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: 2026 Arne Magnus Tveita Løken <212174338+amtl-no@users.noreply.github.com>
# yamllint enable rule:line-length
---
name: 'GitHub Actions Yaml linting'
on: # yamllint disable-line rule:truthy
  push:
    paths:
      - 'data/**.yaml'
      - '.github/**.yaml'
      - '.github/workflows/**.yaml'
      - '.yamllint'
  workflow_dispatch: # yamllint disable-line rule:truthy

jobs:
  yamllint:
    name: 'Lint ${{ matrix.folder }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ['data', '.github/workflows', '.github/dependabot.yaml']

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Yamllint ${{ matrix.folder }}'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '${{ matrix.folder }}'
          yamllint_strict: true
          yamllint_comment: false
